In [27]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# CREATING DATASET

In [28]:
from sklearn.datasets import make_classification

X,Y=make_classification(n_samples=1000,n_classes=2,n_features=2,random_state=42,n_clusters_per_class=1,n_redundant=0)

In [29]:
X

array([[ 0.60103418,  1.5353525 ],
       [ 0.75594526, -1.1723519 ],
       [ 1.35447877, -0.94852841],
       ...,
       [ 2.84431506,  0.21129354],
       [-0.02587554,  1.6192578 ],
       [ 3.64147835,  0.75692519]])

In [30]:
pd.DataFrame(X)[0]
pd.DataFrame(X)[1]

0      1.535353
1     -1.172352
2     -0.948528
3      0.233485
4      0.787514
         ...   
995    0.451639
996   -0.794996
997    0.211294
998    1.619258
999    0.756925
Name: 1, Length: 1000, dtype: float64

# TRAIN TEST SPLIT

In [31]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

# MODEL TRAINING

In [32]:
from sklearn.svm import SVC

svc=SVC(kernel="linear")

svc.fit(x_train,y_train)
pridicted=svc.predict(x_test)

In [33]:
pridicted

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [34]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(y_test,pridicted)
print("The confusion matrix is :",cm)

cr=classification_report(y_test,pridicted)
print("The classifiction report is  :",cr)

ac=accuracy_score(y_test,pridicted)
print(f"The accuracy score is :{ac*100}%")

The confusion matrix is : [[146   1]
 [ 25 128]]
The classifiction report is  :               precision    recall  f1-score   support

           0       0.85      0.99      0.92       147
           1       0.99      0.84      0.91       153

    accuracy                           0.91       300
   macro avg       0.92      0.91      0.91       300
weighted avg       0.92      0.91      0.91       300

The accuracy score is :91.33333333333333%


# IF WE HAVE NON LINEAR DATASET THEN USE RBF

In [35]:
from sklearn.datasets import make_classification

X1,Y1=make_classification(n_classes=2,n_features=2,n_samples=1000,n_clusters_per_class=2,n_redundant=0,random_state=10)

In [36]:
X1

array([[-0.54185501,  0.05720813],
       [ 1.66202688, -0.72758967],
       [ 0.94861229, -0.98298974],
       ...,
       [ 0.29032716, -0.05378418],
       [-0.85577673,  0.06419288],
       [-1.83119322,  1.91963373]])

In [37]:
Y1

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,

In [38]:
from sklearn.model_selection import train_test_split

x_train1,x_test1,y_train1,y_test1=train_test_split(X1,Y1,test_size=0.30,random_state=20)

In [39]:
from sklearn.svm import SVC

rbf=SVC(kernel="rbf")

rbf.fit(x_train1,y_train1)

pridicted1=rbf.predict(x_test1)


In [40]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
cm=confusion_matrix(y_test1,pridicted1)
print("The confusion matrix is :",cm)

cr=classification_report(y_test1,pridicted1)
print("The classifiction report is  :",cr)

ac=accuracy_score(y_test1,pridicted1)
print(f"The accuracy score is :{ac*100}%")

The confusion matrix is : [[137  13]
 [ 19 131]]
The classifiction report is  :               precision    recall  f1-score   support

           0       0.88      0.91      0.90       150
           1       0.91      0.87      0.89       150

    accuracy                           0.89       300
   macro avg       0.89      0.89      0.89       300
weighted avg       0.89      0.89      0.89       300

The accuracy score is :89.33333333333333%


# FOR POLYNOMIAL DATA

In [41]:
from sklearn.datasets import make_classification

X,Y=make_classification(n_classes=2,n_features=2,n_samples=1000,n_clusters_per_class=2,n_redundant=0)


In [42]:
X

array([[ 0.3370136 ,  1.40429831],
       [ 1.27884153,  0.25668817],
       [ 0.70663335,  1.05908479],
       ...,
       [-0.17901897,  0.38635832],
       [-0.73417803,  0.79546499],
       [ 1.34801815,  0.92378702]])

# TRAIN TEST SPLIT

In [43]:
from sklearn.model_selection import train_test_split

x_train2,x_test2,y_train2,y_test2=train_test_split(X,Y,test_size=0.30,random_state=40)



# MODEL TRAINING    

In [44]:
from sklearn.svm import SVC

poly=SVC(kernel="poly")

poly.fit(x_train2,y_train2)

predict3=poly.predict(x_test2)



In [45]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix


ac=accuracy_score(y_test2,predict3)
print(ac)

cr=classification_report(y_test2,predict3)
print(cr)

cm=confusion_matrix(y_test2,predict3)
print(cm)

0.9166666666666666
              precision    recall  f1-score   support

           0       0.90      0.93      0.91       144
           1       0.93      0.90      0.92       156

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[134  10]
 [ 15 141]]


# HYPERPARAMETER TUNING

In [46]:
from sklearn.model_selection import GridSearchCV

param_grid={ "C" :[100,10,1.0,0.1,0.01],
            "gamma" :[100,10,1,0,0.1,0.01],
            "kernel" :["rbf"]
}

In [47]:
grid=GridSearchCV(SVC(),param_grid=param_grid,verbose=3,refit=True,cv=5)

In [48]:
grid.fit(x_train2,y_train2)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV 1/5] END ......C=100, gamma=100, kernel=rbf;, score=0.857 total time=   0.0s
[CV 2/5] END ......C=100, gamma=100, kernel=rbf;, score=0.886 total time=   0.0s
[CV 3/5] END ......C=100, gamma=100, kernel=rbf;, score=0.893 total time=   0.0s
[CV 4/5] END ......C=100, gamma=100, kernel=rbf;, score=0.821 total time=   0.0s
[CV 5/5] END ......C=100, gamma=100, kernel=rbf;, score=0.821 total time=   0.0s
[CV 1/5] END .......C=100, gamma=10, kernel=rbf;, score=0.893 total time=   0.0s
[CV 2/5] END .......C=100, gamma=10, kernel=rbf;, score=0.950 total time=   0.0s
[CV 3/5] END .......C=100, gamma=10, kernel=rbf;, score=0.886 total time=   0.0s
[CV 4/5] END .......C=100, gamma=10, kernel=rbf;, score=0.900 total time=   0.0s
[CV 5/5] END .......C=100, gamma=10, kernel=rbf;, score=0.900 total time=   0.0s
[CV 1/5] END ........C=100, gamma=1, kernel=rbf;, score=0.943 total time=   0.0s
[CV 2/5] END ........C=100, gamma=1, kernel=rbf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'gamma': [100, 10, 1, 0, 0.1, 0.01],
                         'kernel': ['rbf']},
             verbose=3)

In [49]:
predict4=grid.predict(x_test2)



In [50]:
grid.best_params_

{'C': 1.0, 'gamma': 1, 'kernel': 'rbf'}

In [51]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix


ac=accuracy_score(y_test2,predict4)
print(ac*100)

cr=classification_report(y_test2,predict4)
print(cr)

cm=confusion_matrix(y_test2,predict4)

92.33333333333333
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       144
           1       0.93      0.92      0.93       156

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

