In [241]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


# CREATING A DATASET USING SKLEARN

In [242]:
from sklearn.datasets import make_classification

X,Y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=40)

In [243]:
X

array([[ 1.05358353, -1.63100965, -1.52162935, ..., -0.68811061,
        -0.20603675,  1.82640605],
       [ 0.56563904, -0.71337317,  0.3748404 , ...,  0.48316271,
        -0.06432982,  0.14560493],
       [-0.17452797, -1.64683873,  1.39510637, ...,  0.92097236,
        -0.51267623, -1.12275173],
       ...,
       [-0.68288218,  1.18545176, -0.85803065, ...,  1.00055548,
         0.17014193, -0.34837608],
       [-0.96067336, -0.87524644,  0.71882982, ...,  0.21982784,
        -0.48598627,  0.38345252],
       [ 0.45124318,  1.07046131, -1.23282954, ..., -0.63606724,
         0.41634542, -0.23629432]])

In [244]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    1.053584 -1.631010 -1.521629  0.684137  1.272148 -1.232463  1.426312   
1    0.565639 -0.713373  0.374840  0.701392  0.689576 -1.506999  1.344935   
2   -0.174528 -1.646839  1.395106 -1.320707 -0.288653 -0.047564  0.968606   
3   -0.279680 -1.446212  0.675371 -1.299102 -0.414081  0.272949  1.229307   
4   -0.384685 -1.305725 -1.320987 -1.572503 -0.541766  0.698291  1.017966   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.237848  0.705787  0.295287  0.228928  1.601215 -0.507450  0.128792   
996  1.270760 -1.998320  1.021405  0.107361  1.533112 -0.700759 -0.174314   
997 -0.682882  1.185452 -0.858031 -0.561944 -0.819330  2.375653  0.620580   
998 -0.960673 -0.875246  0.718830  0.994626 -1.255988 -0.155227  1.199345   
999  0.451243  1.070461 -1.232830  1.155625  0.616757  1.410694  0.241402   

            7         8         9  
0   -0.688111 -0.206037  1.826406  
1    0.483163 -0.064330  0.145605  
2    0.920972 -0.512676 -1.122752  
3   -0.299387 -0.481318 -0.538196  
4   -0.822524 -0.467078  0.573891  
..        ...       ...       ...  
995 -1.386940  0.505837 -0.208451  
996 -0.212474 -0.257381  1.484148  
997  1.000555  0.170142 -0.348376  
998  0.219828 -0.485986  0.383453  
999 -0.636067  0.416345 -0.236294  

[1000 rows x 10 columns]

In [245]:
Y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [246]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

x_train.shape,x_test.shape,y_train.shape,y_test.shape

((750, 10), (250, 10), (750,), (250,))

# MODEL TRAINING


In [247]:
from sklearn.linear_model import LogisticRegression

logistic=LogisticRegression()

logistic.fit(x_train,y_train)

LogisticRegression()

In [248]:
pridicted=logistic.predict(x_test)

pridicted

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0])

# PERFORMANCE METRICS

In [249]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

ac=accuracy_score(y_test,pridicted)
print(f"The accuracy score is :{ac*100}%")

cm=confusion_matrix(y_test,pridicted)
print("The confusion matrix is : ",cm)

cr=classification_report(y_test,pridicted)
print("the classfication report is : ",cr)

The accuracy score is :86.4%
The confusion matrix is :  [[120  10]
 [ 24  96]]
the classfication report is :                precision    recall  f1-score   support

           0       0.83      0.92      0.88       130
           1       0.91      0.80      0.85       120

    accuracy                           0.86       250
   macro avg       0.87      0.86      0.86       250
weighted avg       0.87      0.86      0.86       250



# HYPERPARAMETER TUNING AND CROSS VALIDATION

In [250]:
model=LogisticRegression()
penalty=('l1', 'l2', 'elasticnet')
c_values=(100,10,1,0.1,0.01)
solver=('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga')

In [251]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [252]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

cv=StratifiedKFold()

grid=GridSearchCV(estimator=model,param_grid=params,scoring="accuracy",cv=cv,n_jobs=-1)

In [253]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': (100, 10, 1, 0.1, 0.01),
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')},
             scoring='accuracy')

In [254]:
grid.fit(x_train,y_train)

c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
250 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver =

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': (100, 10, 1, 0.1, 0.01),
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')},
             scoring='accuracy')

In [255]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [256]:
grid.best_score_*100

np.float64(89.33333333333333)

In [257]:
gridpridicted=grid.predict(x_test)


In [258]:
ac=accuracy_score(y_test,gridpridicted)
print(f"The accuracy score is :{ac*100}%")

cm=confusion_matrix(y_test,gridpridicted)
print("The confusion matrix is : ",cm)

cr=classification_report(y_test,gridpridicted)
print("the classfication report is : ",cr)

The accuracy score is :86.0%
The confusion matrix is :  [[122   8]
 [ 27  93]]
the classfication report is :                precision    recall  f1-score   support

           0       0.82      0.94      0.87       130
           1       0.92      0.78      0.84       120

    accuracy                           0.86       250
   macro avg       0.87      0.86      0.86       250
weighted avg       0.87      0.86      0.86       250



# RANDOMIZED SEARCHCV

In [259]:
model=LogisticRegression()

from sklearn.model_selection import RandomizedSearchCV

randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,scoring="accuracy",cv=5)

In [260]:
randomcv.fit(x_train,y_train)

c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': (100, 10, 1, 0.1, 0.01),
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ('lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga')},
                   scoring='accuracy')

In [261]:
randomcv.best_score_*100

np.float64(88.79999999999998)

In [262]:
randomcv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 100}

In [263]:
pridictedrandom=randomcv.predict(x_test)

In [264]:
ac=accuracy_score(y_test,pridictedrandom)
print(f"The accuracy score is :{ac*100}%")

cm=confusion_matrix(y_test,pridictedrandom)
print("The confusion matrix is : ",cm)

cr=classification_report(y_test,pridictedrandom)
print("the classfication report is : ",cr)

The accuracy score is :86.4%
The confusion matrix is :  [[120  10]
 [ 24  96]]
the classfication report is :                precision    recall  f1-score   support

           0       0.83      0.92      0.88       130
           1       0.91      0.80      0.85       120

    accuracy                           0.86       250
   macro avg       0.87      0.86      0.86       250
weighted avg       0.87      0.86      0.86       250



# LOGISTIC REGRESSION OVR(ONE OVER REST)

In [265]:
X,Y=make_classification(n_samples=1000,n_classes=3,n_informative=3,n_features=10,random_state=42)

In [266]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [267]:
Y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

# TRAIN TEST SPLIT

In [268]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

In [269]:
logistic=LogisticRegression(multi_class="ovr")

logistic.fit(x_train,y_train)


c:\Users\sujal\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [270]:
pridictedovr=logistic.predict(x_test)

In [271]:
ac=accuracy_score(y_test,pridictedovr)
print(f"The accuracy score is :{ac*100}%")

cm=confusion_matrix(y_test,pridictedovr)
print("The confusion matrix is : ",cm)

cr=classification_report(y_test,pridictedovr)
print("the classfication report is : ",cr)

The accuracy score is :68.0%
The confusion matrix is :  [[79 16  8]
 [31 38 27]
 [ 3 11 87]]
the classfication report is :                precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300

